// Generated by CoffeeScript 1.7.1
var FileHandler, JsHandler, url;

url = require('url');

JsHandler = new require('./jsHandler');

FileHandler = new require('./fileHandler');

module.exports = function() {
  var Application;
  Application = (function() {
    function Application(req, res) {
      this.req = req;
      this.res = res;
      this.pathname = url.parse(this.req.url, true);
      console.log(this.pathname);
    }

    Application.prototype.process = function() {
      if (/\/javascripts\//.test(this.pathname.pathname)) {
        (new JsHandler(this.req, this.res, this.pathname)).process();
      } else {
        (new FileHandler(this.req, this.res, this.pathname)).process();
      }
    };

    return Application;

  })();
  return Application;
}();
