// Generated by CoffeeScript 1.7.1
module.exports = function() {
  var Handler;
  Handler = (function() {
    var write;

    function Handler(req, res, pathInfo) {
      this.req = req;
      this.res = res;
      this.pathInfo = pathInfo;
    }

    Handler.prototype.contentType = function() {
      throw new Error('must be implemented!');
    };

    Handler.prototype.process = function() {
      throw new Error('must be implemented!');
    };

    Handler.prototype.pathname = function() {
      return pathInfo.pathname;
    };

    write = function(data, status, headers) {
      if (status == null) {
        status = 200;
      }
      if (headers == null) {
        headers = {};
      }
      headers['contentType'] || (headers['contentType'] = this.contentType());
      headers['contentLength'] || (headers['contentLength'] = Buffer.byteLength(data));
      this.res.writeHead(status, headers);
      this.res.write(data, 'utf-8');
      return this.res.end;
    };

    return Handler;

  })();
  return Handler;
};
