// Generated by CoffeeScript 1.7.1
var CoffeeScript, Handler, fs,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

fs = require('fs');

Handler = require('./handler');

CoffeeScript = require('coffee-script');

module.exports = function() {
  var JsHandler;
  return JsHandler = (function(_super) {
    var contentType, process;

    __extends(JsHandler, _super);

    function JsHandler() {
      return JsHandler.__super__.constructor.apply(this, arguments);
    }

    contentType = function() {
      return "application/x-javascript";
    };

    JsHandler.prototype.pathname = function() {
      var file;
      file = (/\/javascripts\/(.+)\.js&/.exec(this.pathInfo.pathname))[1];
      return "" + file + ".coffee";
    };

    process = function() {
      console.log("src/" + (this.pathname()));
      return fs.readFile("src/" + (this.pathname()), "utf-8", (function(_this) {
        return function(err, data) {
          if (err != null) {
            return _this.write("ooops!, 404", 404);
          } else {
            return _this.write(CoffeeScript.compile(data));
          }
        };
      })(this));
    };

    return JsHandler;

  })(Handler);
};
